# Generated by Django 4.0.4 on 2023-07-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_packages_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='p_id',
            new_name='id',
        ),
    ]
