# Generated by Django 4.0.4 on 2023-07-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_rename_p_id_packages_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='id',
            new_name='p_id',
        ),
    ]
